### ISSUE TITLE
配置更新的时候出现错误

### ISSUE THREAD

**Issue by realotz** [go-kratos/kube#2]
测试配置文件
a.yaml:
database:
  mysql:
    dsn: "root:Test@tcp(mysql.database.svc.cluster.local:3306)/test?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
    active: 20
    idle: 10
    idle_timeout: 3600
  redis:
    addr: "redis-master.redis.svc.cluster.local:6379"
    password: ""
    db: 4

b.yaml:
application:
  expire: 3600

错误结果如下
在 n.Load() != v.Load()对比判断的时候报错

`panic: runtime error: comparing uncomparable type map[string]interface {}

goroutine 9 [running]:
github.com/go-kratos/kratos/v2/config.(*config).watch.func1(0x2233f40, 0xc0003835f0, 0x236bae0, 0xc0003835e0, 0xc000592800)
	/Users/real/go/src/kratos/github.com/realotz/kube-example/vendor/github.com/go-kratos/kratos/v2/config/config.go:61 +0x265
sync.(*Map).Range(0xc000149ce0, 0xc000017fa0)
	/usr/local/go/src/sync/map.go:345 +0x1d9
github.com/go-kratos/kratos/v2/config.(*config).watch(0xc000149ce0, 0xc00058e1c0, 0x264d8c0, 0xc0002a24b0)
	/Users/real/go/src/kratos/github.com/realotz/kube-example/vendor/github.com/go-kratos/kratos/v2/config/config.go:57 +0x72
created by github.com/go-kratos/kratos/v2/config.(*config).Load
	/Users/real/go/src/kratos/github.com/realotz/kube-example/vendor/github.com/go-kratos/kratos/v2/config/config.go:86 +0x205
exit status 2
make: *** [run] Error 1`

此外 Next修改为array后
发现对c.cached.Range的比对结果是重复的，原先watchers与KeyValue是一一对应的。以下代码for循环中有逻辑问题
`c.cached.Range(func(key, value interface{}) bool {
		k := key.(string)
		v := value.(Value)
		for _, r := range c.resolvers {
			if n := r.Resolve(k); n != nil && n.Load() != v.Load() {
				v.Store(n.Load())
				if o, ok := c.observers.Load(k); ok {
					o.(Observer)(k, v)
				}
			}
		}
		return true
	})`

**Comment by tonybase** [comment]
这个已经修复过来了
